version: '3.7'

services:
  customer-web-api:
    container_name: webapi
    build:
      context: . 
      dockerfile: src/Presentation/Hahn.WebApi/Dockerfile
    ports:
      - "5010:80"
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'
      DOTNET_ENVIRONMENT: 'Development'
    depends_on:
      - sqlserver
    networks:
      - hahn

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Aa12345678"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    networks:
      - hahn

networks:
  hahn:
